name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300
      - name: Restore tools
        run: dotnet tool restore
        working-directory: ./Src
      - name: Build templates
        # TargetFramework specified so this only runs once rather than per framework
        run: dotnet msbuild -t:TextTemplateTransform -p:TargetFramework=NA Src
      - name: Release Build
        run: dotnet build --configuration=Release -p:TreatWarningsAsErrors=true Src
      - name: CPU Tests
        run: dotnet test --configuration=Release ./Src/ILGPU.Algorithms.Tests.CPU
      - name: Create NuGet package
        if: runner.os == 'Windows'
        run: dotnet pack --configuration=Release -o . Src
      - name: Fix NuGet Symbols Package
        if: runner.os == 'Windows'
        run: |
          # WORKAROUND: The Symbols package should only contain Portable
          # PDBs (no Windows PDBs allowed). Transfer ILGPU.pdb from Symbols
          # package to Main NuGet package. Can be removed after updating
          # ILGPU from net47 to net472.

          # Get path to the Main and Symbols NuGet packages
          $releaseDir = '.\Bin\Release'
          $packageDir = '.'
          $mainPkgPath =
            Get-ChildItem -Path $packageDir -Filter ILGPU.Algorithms.*.nupkg `
            | Select-Object -First 1 -ExpandProperty Fullname
          $symbolsPkgPath =
            Get-ChildItem -Path $packageDir -Filter ILGPU.Algorithms.*.snupkg `
            | Select-Object -First 1 -ExpandProperty Fullname

          # Transfer ILGPU.Algorithms.pdb from the Symbols to Main NuGet package
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          $pdbEntryPath = 'lib/net47/ILGPU.Algorithms.pdb'

          $mainPkgZip = [System.IO.Compression.ZipFile]::Open(
            $mainPkgPath,
            'Update')
          [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile(
              $mainPkgZip,
              "$releaseDir\net47\ILGPU.Algorithms.pdb",
              $pdbEntryPath);
          $mainPkgZip.Dispose()

          $symbolsPkgZip = [System.IO.Compression.ZipFile]::Open(
            $symbolsPkgPath,
            'Update')
          $symbolsPkgZip.GetEntry($pdbEntryPath).Delete();
          $symbolsPkgZip.Dispose()

      - name: Upload NuGet package artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: ILGPU.Algorithms.*.*nupkg

  publish-nuget:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-and-test
    runs-on: windows-latest
    steps:
      - name: Download NuGet package artifact
        uses: actions/download-artifact@v2
        with:
          name: nuget-package
      - name: Publish to NuGet
        shell: bash
        run: dotnet nuget push ILGPU.Algorithms.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
